Added resource for linux and windows virtual machine
hashicorp/terraform-provider-azurestack pull request #148
Opened 2022-02-15 20:42 UTC by coderGo93

- Added a resource, doc and test for linux virtual machine called `azurestack_linux_virtual_machine`
- Added a resource, doc and test for windows virtual machine called `azurestack_windows_virtual_machine`
- Added various files that are needed for the resources linux and windows virtual machine
- Updated vendor

2022-02-24 19:26 UTC, coderGo93 commented
Closed temporarily in favor of other pending task, will re-open after finished the other pending tasks.

2022-03-02 22:41 UTC, coderGo93 commented
Re-opened with tests for linux and windows added

2022-03-11 21:03 UTC, katbyte commented on internal/services/compute/network_interface.go
> +// with the specified Network Interface
```suggestion
// retrieveIPAddressesForNIC returns the Public and Private IP Addresses associated with the specified Network Interface
```

2022-03-11 21:03 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-azurestack?pullRequest=148)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-azurestack?pullRequest=148)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**0** out of **2** committers have signed the CLA.


- [ ] coderGo93
- [ ] katbyte

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-azurestack?pullRequest=148).</sub>

2022-03-18 01:35 UTC, katbyte requested changes
can we plase fix the tests?

<img width="743" alt="image" src="https://user-images.githubusercontent.com/1638467/158920619-afbc3e06-adf1-405c-955f-f15a55a34984.png">

<img width="544" alt="image" src="https://user-images.githubusercontent.com/1638467/158920637-3e243048-f213-4aa0-9ec8-7eb5b94dc473.png">


etc

2022-03-18 03:25 UTC, coderGo93 commented
> can we plase fix the tests?
> 
> <img alt="image" width="743" src="https://user-images.githubusercontent.com/1638467/158920619-afbc3e06-adf1-405c-955f-f15a55a34984.png">
> 
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/1638467/158920637-3e243048-f213-4aa0-9ec8-7eb5b94dc473.png">
> 
> etc

The investigation still ongoing from the MSFT support  and confirm it if it’s supported for multiple network interfaces because it works with a single network interface but not multiple.

2022-03-29 04:02 UTC, katbyte requested changes

2022-03-29 17:17 UTC, coderGo93 commented on internal/provider/features_test.go
> +					},
good eye, for now we don't have these resources, will remove them

2022-03-30 00:37 UTC, katbyte approved these changes
Thanks @coderGo93 - LGTM now 🌻

2022-03-30 00:37 UTC, merged